hmmm
* kshrc updates

diff --git a/etc/kshrc b/etc/kshrc
--- a/etc/kshrc
+++ b/etc/kshrc
@@ -8,18 +8,27 @@ set -o vi
 
 # prompt
 _prompt() {
-	if [ $? -ne 0 -a $? -ne 130 ]; then
-		printf '\033[31m'
+	exit_code="$?"
+
+	if [ "$(pwd)" != "$HOME" ]; then
+		printf '\033[38m%s' "$(basename "$(pwd)")"
 	else
-		printf '\033[1m\033[30m'
+		printf '\033[0m'
 	fi
 
+	# exit code
+	if [ "$exit_code" -eq "0" ]; then
+		printf '\033[90m'
+	else
+		printf '\033[31m'
+	fi
+
+	# root ?
 	if [ $(id -u) -ne 0 ]; then
 		printf '$'
 	else
 		printf '#'
 	fi
-
 	printf '\033[0m'
 }
 export PS1='$(_prompt) '
@@ -30,6 +39,7 @@ export VIS_PATH="$HOME/etc/vis"
 # alias
 alias \!\!='$(fc -l | tail -1 | cut -f 2)'
 alias f='finger'
+alias gls='git status -s'
 alias h='history -r | less'
 alias j='jobs -l'
 alias la='ls -a'
@@ -47,7 +57,7 @@ if [ $(id -u) -ne 0 ]; then
 	esac
 fi
 
-# setup a tmux session for development
+# setup a tmux session for "development"
 setupdev() {
 	tmux new-session -d
 	tmux split-window -v
@@ -73,15 +83,23 @@ fname() {
 	echo "`date '+%b.%d-%H%M'`"
 }
 
+# new blog post
+blog() {
+	title="${1:-title}"
+	date="$(date '+%F')"
+	vise "${HOME}/usr/txt/${date}-${title}.md"
+}
+
 # make a dir and cd into it
 mkcd() {
-	if [ $# -eq 1 ]; then 
-		eval local path=\$$#
-	else
+	if [ $# -lt 1 ]; then 
 		echo "insufficient arguments given..."
 		return 1
 	fi
-	mkdir -p $@
+
+	eval local path=\$$#
+
+	mkdir $@
 	cd "$path"
 }
 
